### ISSUE TITLE
to_left used before being defined

### ISSUE THREAD

**Issue by bfgray3** [edgararuiz/tidypredict#21]
Hi!  I've noticed that in `parsemodel.R`, the variable `to_left` is used before being defined.  I believe this would affect `parse_model.randomForest`.

```
$ grep -rnw ./R -e to_left
./R/parsemodel.R:212:        paste0(ifelse(to_left, "left", "right"))
./R/parsemodel.R:224:    to_left <- length(left) > 0
```

**Comment by edgararuiz** [comment]
Hi @bfgray3 , thank you so much for reporting this.  I believe this is ok because the function that call `get_path()` passes only the ends, meaning the prediction rows, which contain no left or right numbers.  That's why it's ok to evaluate which left or right daughter value matches the row ID after that `if` condition.  I'll double check, but I think is correct so far.

BTW - I made some improvement with evaluating multiple paths during the implementation of the `ranger` support, so I may be doing some refinements to the `randomForest` parser, your keen eye will be welcome after those improvements are made. 

Thanks again!
